export default {
  login: "szryldrm",
  id: 11529594,
  node_id: "MDQ6VXNlcjExNTI5NTk0",
  avatar_url: "https://avatars1.githubusercontent.com/u/11529594?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/szryldrm",
  html_url: "https://github.com/szryldrm",
  followers_url: "https://api.github.com/users/szryldrm/followers",
  following_url: "https://api.github.com/users/szryldrm/following{/other_user}",
  gists_url: "https://api.github.com/users/szryldrm/gists{/gist_id}",
  starred_url: "https://api.github.com/users/szryldrm/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/szryldrm/subscriptions",
  organizations_url: "https://api.github.com/users/szryldrm/orgs",
  repos_url: "https://api.github.com/users/szryldrm/repos",
  events_url: "https://api.github.com/users/szryldrm/events{/privacy}",
  received_events_url: "https://api.github.com/users/szryldrm/received_events",
  type: "User",
  site_admin: false,
  name: "Sezer YILDIRIM",
  company: null,
  blog: "https://www.sezeryildirim.com",
  location: "Manisa, TURKEY",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 27,
  public_gists: 0,
  followers: 4,
  following: 6,
  created_at: "2015-03-17T23:39:52Z",
  updated_at: "2020-08-18T11:57:35Z",
};
