export default [
  {
    login: "onurhizlan",
    id: 33904718,
    node_id: "MDQ6VXNlcjMzOTA0NzE4",
    avatar_url: "https://avatars3.githubusercontent.com/u/33904718?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/onurhizlan",
    html_url: "https://github.com/onurhizlan",
    followers_url: "https://api.github.com/users/onurhizlan/followers",
    following_url: "https://api.github.com/users/onurhizlan/following{/other_user}",
    gists_url: "https://api.github.com/users/onurhizlan/gists{/gist_id}",
    starred_url: "https://api.github.com/users/onurhizlan/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/onurhizlan/subscriptions",
    organizations_url: "https://api.github.com/users/onurhizlan/orgs",
    repos_url: "https://api.github.com/users/onurhizlan/repos",
    events_url: "https://api.github.com/users/onurhizlan/events{/privacy}",
    received_events_url: "https://api.github.com/users/onurhizlan/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "VolkanGurbuz",
    id: 24397550,
    node_id: "MDQ6VXNlcjI0Mzk3NTUw",
    avatar_url: "https://avatars0.githubusercontent.com/u/24397550?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/VolkanGurbuz",
    html_url: "https://github.com/VolkanGurbuz",
    followers_url: "https://api.github.com/users/VolkanGurbuz/followers",
    following_url: "https://api.github.com/users/VolkanGurbuz/following{/other_user}",
    gists_url: "https://api.github.com/users/VolkanGurbuz/gists{/gist_id}",
    starred_url: "https://api.github.com/users/VolkanGurbuz/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/VolkanGurbuz/subscriptions",
    organizations_url: "https://api.github.com/users/VolkanGurbuz/orgs",
    repos_url: "https://api.github.com/users/VolkanGurbuz/repos",
    events_url: "https://api.github.com/users/VolkanGurbuz/events{/privacy}",
    received_events_url: "https://api.github.com/users/VolkanGurbuz/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "okayonbasi",
    id: 43735222,
    node_id: "MDQ6VXNlcjQzNzM1MjIy",
    avatar_url: "https://avatars0.githubusercontent.com/u/43735222?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/okayonbasi",
    html_url: "https://github.com/okayonbasi",
    followers_url: "https://api.github.com/users/okayonbasi/followers",
    following_url: "https://api.github.com/users/okayonbasi/following{/other_user}",
    gists_url: "https://api.github.com/users/okayonbasi/gists{/gist_id}",
    starred_url: "https://api.github.com/users/okayonbasi/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/okayonbasi/subscriptions",
    organizations_url: "https://api.github.com/users/okayonbasi/orgs",
    repos_url: "https://api.github.com/users/okayonbasi/repos",
    events_url: "https://api.github.com/users/okayonbasi/events{/privacy}",
    received_events_url: "https://api.github.com/users/okayonbasi/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Kaan-Uzun",
    id: 48808356,
    node_id: "MDQ6VXNlcjQ4ODA4MzU2",
    avatar_url: "https://avatars1.githubusercontent.com/u/48808356?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Kaan-Uzun",
    html_url: "https://github.com/Kaan-Uzun",
    followers_url: "https://api.github.com/users/Kaan-Uzun/followers",
    following_url: "https://api.github.com/users/Kaan-Uzun/following{/other_user}",
    gists_url: "https://api.github.com/users/Kaan-Uzun/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Kaan-Uzun/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Kaan-Uzun/subscriptions",
    organizations_url: "https://api.github.com/users/Kaan-Uzun/orgs",
    repos_url: "https://api.github.com/users/Kaan-Uzun/repos",
    events_url: "https://api.github.com/users/Kaan-Uzun/events{/privacy}",
    received_events_url: "https://api.github.com/users/Kaan-Uzun/received_events",
    type: "User",
    site_admin: false,
  },
];
